### ISSUE TITLE
Visual Studio 2019 crashes when connecting Web Resource Deployer

### ISSUE THREAD

**Issue by BKamleitner** [tsharp/D365DeveloperExtensions#17]
Hello, 

suddenly my vs 2019 crashes when connecting with Web Resource Deployer. I wonder if it got something to do with Profiles and VS Solution Configurations. When VS 2019 crashes it terminated immediatly. I attached a screen of web resource deployer just before the crash, i cannot remebember if i ever used Profiles but i think it is always empty but worked so far. In application log i can see:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WebResourceDeployer.Config.Mapping.![webresourcedeployer](https://user-images.githubusercontent.com/30052849/141288520-f66722b7-e96d-4024-949f-3689e1521e44.JPG)(System.String, D365DeveloperExtensions.Core.Models.SpklConfig)
   at WebResourceDeployer.Config.Mapping.HandleSpklMappings(EnvDTE.Project, System.String, System.Collections.ObjectModel.ObservableCollection`1<WebResourceDeployer.ViewModels.WebResourceItem>)
   at WebResourceDeployer.WebResourceDeployerWindow+<GetWebResources>d__76.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at WebResourceDeployer.WebResourceDeployerWindow+<GetCrmData>d__74.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at WebResourceDeployer.WebResourceDeployerWindow+<LoadData>d__38.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by BKamleitner** [comment]
![webresourcedeployer_ok](https://user-images.githubusercontent.com/30052849/141312737-52dd9282-d4f0-4f6e-8620-138461b518eb.JPG)

I dont know what has changed, but now when opening there is a profile and everything is fine.
